pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('Lint HTML') {
            steps {
                sh 'tidy -q -e ci-cd-pipelines/jenkins-pipeline/*.html'
            }
        }
        stage('Scan') {
            steps {
                aquaMicroscanner imageName: 'alpine:latest', notCompliesCmd: 'exit 4', onDisallowed: 'fail', outputFormat: 'html'
            }
        }
        stage('Upload to AWS') {
            steps {
                withAWS(region:'us-east-1', credentials: 'jenkins') {
                    s3Upload(pathStyleAccessEnabled:true, payloadSigningEnabled: true, file:'ci-cd-pipelines/jenkins-pipeline/index.html', bucket:'udacity-pipeline-s3')
                }
            }
        }
    }
}